SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `student2`;
CREATE TABLE `student2` (
`SNO` decimal(6,0) NOT NULL,
`SNAME` char(3) NOT NULL,
`AGE` decimal(3,0),
`SEX` char(2)DEFAULT NULL,
`BPLACE` char(20) DEFAULT NULL,
PRIMARY KEY(`SNO`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
SET FOREIGN_KEY_CHECKS=1;